Install flake8, black and isort as linters and reformatters
borisliao/mbox pull request #114
Opened 2021-06-27 20:44 UTC by Exsects

See #105 and #113 for reference.

2021-06-28 18:51 UTC, Karan-Jain approved these changes, later dismissed

2021-06-28 19:54 UTC, Karan-Jain commented
Looks like these are going to run with pipeline. Nice!

2021-07-01 01:47 UTC, borisliao requested changes
Add back pytest.ini file, that might fix unit tests

2021-07-01 01:47 UTC, borisliao commented on .vscode/launch.json
> -{
Add back this file

2021-07-01 01:47 UTC, borisliao commented on .vscode/settings.json
> -{
Add back this file

2021-07-01 02:25 UTC, borisliao approved these changes
LGTM

2021-07-01 02:36 UTC, Karan-Jain approved these changes

2021-07-01 02:36 UTC, merged