Cleaned up README.md
borisliao/mbox pull request #34
Opened 2021-05-01 03:40 UTC by Exsects

- Cleaned up README.md 
- Renamed and updated the following Wiki pages:
  -  Installing FFMPEG for mbox
  -  Setting up a Bot Account on the Discord Developer Portal 
-  Fixed images not showing up correctly for Wiki pages.

2021-05-01 04:22 UTC, Karan-Jain commented
Consider adding a comment at the dtart of the readme -> use python instead of pythom3 for windows users.

This we dont need to havs a seperate python command for window and mac/linux

2021-05-01 18:37 UTC, borisliao requested changes

2021-05-01 18:37 UTC, borisliao commented on README.md
> +    *For Windows users*, if you do not bash already installed, you can download Git Bash [here]((https://git-scm.com/download/win))
Bash is not necessary needed in windows, only git. This download comes with git bash but primarily is for installing git.

2021-05-01 19:56 UTC, Karan-Jain approved these changes

2021-05-01 19:56 UTC, Karan-Jain commented on README.md
> +
Remove the / after the venv, for windows users .


And it doesnt need to be venv, I had originally put "venv name" to give devs a choice. 

The Venv is local and so its is something that is not going into the codebase. So devs can name it whatever they want

2021-05-01 19:56 UTC, Karan-Jain approved these changes, later dismissed

2021-05-01 19:57 UTC, AvJain submitted a review, later dismissed

2021-05-01 21:45 UTC, borisliao submitted a review, later dismissed
Either works but welcome sounds better then welcomed.

2021-05-01 21:45 UTC, borisliao commented on README.md
> +Pull requests are welcomed. For major changes, please open an issue first to discuss what you would like to change.
```suggestion
Pull requests are welcome. For major changes, please open an issue first to discuss what you would like to change.
```

2021-05-02 00:43 UTC, borisliao approved these changes

2021-05-03 20:26 UTC, borisliao approved these changes

2021-05-03 20:28 UTC, AvJain approved these changes
Changes look good

2021-05-03 20:31 UTC, borisliao approved these changes
Looks great! Nothing has changed!!

2021-05-03 20:31 UTC, AvJain approved these changes
Nice changes

2021-05-03 20:32 UTC, merged